version: '3.9'
services:
  web:
    container_name: web_service
    volumes:
      - db_data:/data/
      - nodes:/node_modules/
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - '9000:3000' 
    
volumes:
    db_data: {}
   

